#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WebView.Droid.Resource", IsApplication=true)]

namespace WebView.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int descreaseSizeAnimation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int increaseSize = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int splash_fade_in = 2131034114;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int constraintSet = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int layout_constraintBaseline_creator = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int layout_constraintBaseline_toBaselineOf = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_constraintBottom_creator = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int layout_constraintBottom_toBottomOf = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int layout_constraintBottom_toTopOf = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int layout_constraintDimensionRatio = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constraintEnd_toEndOf = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constraintEnd_toStartOf = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintGuide_begin = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintGuide_end = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintGuide_percent = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintHeight_default = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintHeight_max = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintHeight_min = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintHorizontal_bias = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintHorizontal_chainStyle = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintHorizontal_weight = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintLeft_creator = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintLeft_toLeftOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintLeft_toRightOf = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintRight_creator = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintRight_toLeftOf = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintRight_toRightOf = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintStart_toEndOf = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintStart_toStartOf = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintTop_creator = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintTop_toBottomOf = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintTop_toTopOf = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintVertical_bias = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintVertical_chainStyle = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintVertical_weight = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintWidth_default = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintWidth_max = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintWidth_min = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_editor_absoluteX = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_editor_absoluteY = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_goneMarginBottom = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_goneMarginEnd = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_goneMarginLeft = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_goneMarginRight = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_goneMarginStart = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_goneMarginTop = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_optimizationLevel = 2130772011;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int colorAccent = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int colorPrimary = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int colorPrimaryDark = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int ring1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ring2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ring3 = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int white = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int fab_margin = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circular = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int expand = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo_shape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ring1_shape = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash_gradient_view = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SplashScreenGradient = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int all = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int basic = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int chains = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int chatBox = 2131296266;
			
			// aapt resource value: 0x7f090010
			public const int label = 2131296272;
			
			// aapt resource value: 0x7f09000d
			public const int logoImage = 2131296269;
			
			// aapt resource value: 0x7f090008
			public const int none = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int packed = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int parent = 2131296256;
			
			// aapt resource value: 0x7f090011
			public const int progress1 = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int progressBar = 2131296268;
			
			// aapt resource value: 0x7f090014
			public const int ring1 = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int ring2 = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int ring3 = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int shape1 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int shape2 = 2131296271;
			
			// aapt resource value: 0x7f090001
			public const int spread = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int spread_inside = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int switchBtn = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int webview = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int wrap = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int splashScreen = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int splashScreenw2 = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int expand = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int title_activity_loading = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_constraintSet = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 48;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_elevation = 21;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginEnd = 19;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_layout_marginStart = 18;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotationX = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationY = 17;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_translationZ = 20;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 22
			public const int ConstraintSet_layout_constraintBaseline_creator = 22;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constraintBottom_creator = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintDimensionRatio = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintGuide_begin = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintGuide_end = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintGuide_percent = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintHeight_default = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintHeight_max = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintHeight_min = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintHorizontal_bias = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintHorizontal_weight = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintLeft_creator = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintRight_creator = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintRight_toRightOf = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintStart_toEndOf = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintStart_toStartOf = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintTop_creator = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintTop_toTopOf = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintVertical_bias = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintVertical_weight = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintWidth_default = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintWidth_max = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintWidth_min = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_editor_absoluteX = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_editor_absoluteY = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_goneMarginBottom = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_goneMarginEnd = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_goneMarginLeft = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_goneMarginRight = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_goneMarginStart = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_goneMarginTop = 63;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
